import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

const NotoSans = Noto_Sans_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${NotoSans.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
